apiVersion: v1
kind: ConfigMap
metadata:
  name: mcs-config
  namespace: mcs-ai-platform
data:
  SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017/mcs_ai_platform"
  APP_STORAGE_PATH: "/app/uploads"
  CORS_ALLOWED_ORIGINS: "http://mcs-ai-platform.local,http://localhost:3000"
  LLM_MOCK_ENABLED: "false"
  OPENAI_BASE_URL: "https://api.openai.com/v1"
  LLM_EMBEDDING_MODEL: "text-embedding-3-small"
  OLLAMA_BASE_URL: "http://localhost:11434"
  BACKEND_URL: "http://backend-service:8081"
