package com.mcs.aiplatform.audit;

public enum AuditAction {
    USER_LOGIN, USER_REGISTER,
    AGENT_CREATE, AGENT_UPDATE, AGENT_DELETE, AGENT_DISABLE,
    CHAT_MESSAGE,
    DOCUMENT_UPLOAD, DOCUMENT_DELETE,
    WORKFLOW_CREATE, WORKFLOW_EXECUTE, WORKFLOW_DELETE,
    API_KEY_CREATE, API_KEY_REVOKE,
    ORG_CREATE, ORG_MEMBER_INVITE, ORG_MEMBER_REMOVE,
    SUBSCRIPTION_UPGRADE,
    INTEGRATION_CREATE, INTEGRATION_DELETE,
    MARKETPLACE_PUBLISH, MARKETPLACE_CLONE
}
